# Generated by Django 6.0.4 on 2026-05-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='created_at',
        ),
    ]
